[package]
name = "line_endings"
version = "0.1.0"
authors = ["Finlay <finlay@blackfordanalysis.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
